version: "3.8"
services:
  cypress:
    build: .
    environment:
      - "CYPRESS_BASE_URL=http://host.docker.internal:3000"
    working_dir: /e2e
    volumes:
      - .:/e2e
    command: ["npx", "cypress", "run"]
