version: "3.8"
services:
  cypress:
    image: cypress/included:13.6.0
    environment:
      - CYPRESS_BASE_URL=http://host.docker.internal:3000
    working_dir: /e2e
    volumes:
      - .:/e2e
      - ./entrypoint.sh:/e2e/entrypoint.sh
    entrypoint: /bin/bash
    command: ["/e2e/entrypoint.sh"]
